// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrAXU8etBoHNrB3mcS1esoWb3w0Fv4-M4',
    appId: '1:777496136617:web:a820fbbd382a9a47c452b8',
    messagingSenderId: '777496136617',
    projectId: 'foodlens-5d453',
    authDomain: 'foodlens-5d453.firebaseapp.com',
    storageBucket: 'foodlens-5d453.firebasestorage.app',
    measurementId: 'G-XNJXXLPNV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qZXk_pmLgKUSCQgCHysLk7r29b3f3pc',
    appId: '1:777496136617:android:8d42481a4a57ceaec452b8',
    messagingSenderId: '777496136617',
    projectId: 'foodlens-5d453',
    storageBucket: 'foodlens-5d453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1aqk4fUZNtuDQcsuBptZIsEuh6McDVDk',
    appId: '1:777496136617:ios:d88115cf55908918c452b8',
    messagingSenderId: '777496136617',
    projectId: 'foodlens-5d453',
    storageBucket: 'foodlens-5d453.firebasestorage.app',
    iosClientId: '777496136617-m6b6f2visor37n6lsf5u76qa23hndml9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1aqk4fUZNtuDQcsuBptZIsEuh6McDVDk',
    appId: '1:777496136617:ios:d88115cf55908918c452b8',
    messagingSenderId: '777496136617',
    projectId: 'foodlens-5d453',
    storageBucket: 'foodlens-5d453.firebasestorage.app',
    iosClientId: '777496136617-m6b6f2visor37n6lsf5u76qa23hndml9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrAXU8etBoHNrB3mcS1esoWb3w0Fv4-M4',
    appId: '1:777496136617:web:b36d66428667aa97c452b8',
    messagingSenderId: '777496136617',
    projectId: 'foodlens-5d453',
    authDomain: 'foodlens-5d453.firebaseapp.com',
    storageBucket: 'foodlens-5d453.firebasestorage.app',
    measurementId: 'G-Q642RNPXF3',
  );
}
